name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and verify compilation
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ci/Dockerfile
        push: false
        load: true
        tags: rtl-icecast:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
