name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Copy source files
      run: |
        cd ${{ github.workspace }}
        # Copy source files to ci directory
        cp Makefile config.cpp config.h rtl_icecast.cpp ci/
        echo "Files copied to ci directory:"
        ls -l ci/
    
    - name: Build Docker image
      run: |
        cd ${{ github.workspace }}/ci
        docker build -t rtl-icecast:test .