name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Prepare build context
      run: |
        cd ${{ github.workspace }}
        # Create staging directory
        mkdir -p ci/build
        # Copy files to staging
        cp Makefile config.cpp config.h rtl_icecast.cpp ci/build/
        # Debug output
        echo "=== Source files ==="
        ls -l Makefile config.cpp config.h rtl_icecast.cpp
        echo "=== Staging directory contents ==="
        ls -l ci/build/
        echo "=== First line of each file ==="
        for f in ci/build/*; do
          echo "=== $f ==="
          head -n 1 "$f"
        done
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and verify compilation
      uses: docker/build-push-action@v4
      with:
        context: ${{ github.workspace }}/ci/build
        file: ${{ github.workspace }}/ci/Dockerfile
        push: false
        load: true
        tags: rtl-icecast:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        no-cache: true
        progress: plain