name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Copy source files
      run: |
        cd ${{ github.workspace }}
        # Copy source files to ci directory
        cp Makefile config.cpp config.h rtl_icecast.cpp ci/
        # Make build script executable
        chmod +x ci/build_docker.sh
        echo "Files in ci directory:"
        ls -l ci/
    
    - name: Build Docker image
      run: |
        # Build with progress and no cache
        DOCKER_BUILDKIT=1 docker build -f ci/Dockerfile --progress=plain --no-cache -t rtl-icecast:test .