name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Debug workspace
      run: |
        echo "Current directory: $PWD"
        echo "GitHub workspace: ${{ github.workspace }}"
        echo "Source files:"
        ls -l ${{ github.workspace }}/*.{cpp,h,Makefile}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and verify compilation
      uses: docker/build-push-action@v4
      with:
        context: ${{ github.workspace }}
        file: ${{ github.workspace }}/ci/Dockerfile
        push: false
        load: true
        tags: rtl-icecast:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        no-cache: true
        progress: plain