name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Debug workspace
      run: |
        echo "Current directory: $PWD"
        echo "GitHub workspace: ${{ github.workspace }}"
        echo "Directory contents of workspace:"
        ls -la ${{ github.workspace }}
        echo "Directory contents of ci:"
        ls -la ${{ github.workspace }}/ci
        echo "Parent directory:"
        ls -la ..
        echo "Full tree from workspace:"
        cd ${{ github.workspace }} && tree
        echo "Docker version:"
        docker version
    
    - name: Copy source files to ci directory
      run: |
        cp ${{ github.workspace }}/Makefile ${{ github.workspace }}/ci/
        cp ${{ github.workspace }}/config.cpp ${{ github.workspace }}/ci/
        cp ${{ github.workspace }}/config.h ${{ github.workspace }}/ci/
        cp ${{ github.workspace }}/rtl_icecast.cpp ${{ github.workspace }}/ci/
        echo "Files copied to ci directory:"
        ls -la ${{ github.workspace }}/ci/
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and verify compilation
      uses: docker/build-push-action@v4
      with:
        context: ${{ github.workspace }}/ci
        file: ${{ github.workspace }}/ci/Dockerfile
        push: false
        load: true
        tags: rtl-icecast:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        no-cache: true
        progress: plain