name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Debug workspace
      run: |
        echo "Current directory: $PWD"
        echo "GitHub workspace: ${{ github.workspace }}"
        echo "Source files in workspace:"
        find ${{ github.workspace }} -type f -name "*.cpp" -o -name "*.h" -o -name "Makefile"
        echo "CI directory contents before copy:"
        ls -la ${{ github.workspace }}/ci/
    
    - name: Copy source files to ci directory
      run: |
        cd ${{ github.workspace }}
        echo "Copying files from $(pwd) to ci/"
        cp ./Makefile ./config.cpp ./config.h ./rtl_icecast.cpp ./ci/
        echo "CI directory contents after copy:"
        ls -la ./ci/
        echo "Verifying file contents:"
        for f in ci/Makefile ci/config.cpp ci/config.h ci/rtl_icecast.cpp; do
          echo "=== $f ==="
          head -n 1 "$f" || echo "Failed to read $f"
        done
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and verify compilation
      uses: docker/build-push-action@v4
      with:
        context: ${{ github.workspace }}/ci
        file: ${{ github.workspace }}/ci/Dockerfile
        push: false
        load: true
        tags: rtl-icecast:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        no-cache: true
        progress: plain