name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures the full repo history is available

      - name: Verify files
        run: |
          echo "Current working directory: $PWD"
          echo "GitHub workspace: ${{ github.workspace }}"
          ls -laR

      - name: Build Docker image
        run: |
          docker build -t rtl-icecast:latest -f ci/Dockerfile .

      - name: Run Docker container
        run: |
          docker run -d --name rtl-icecast rtl-icecast:latest